### ISSUE TITLE
Dependency Exceptions

### ISSUE THREAD

**Issue by rmbrowndigital** [freesimpleryan/groundschool-2#1]
```98.52 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lessonController': Unsatisfied dependency expressed through field 'chapterService': Error creating bean with name 'chapterService': Unsatisfied dependency expressed through field 'questionService': Error creating bean with name 'questionService': Unsatisfied dependency expressed through field 'answerService': Error creating bean with name 'answerService' defined in file [/usr/src/groundschool/target/classes/com/starfireaviation/groundschool/service/AnswerService.class]: Unexpected exception during bean creation```

**Comment by rmbrowndigital** [comment]
```43.93 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'imageController': Unsatisfied dependency expressed through field 'imageService': Error creating bean with name 'imageService': Invocation of init method failed```

**Comment by rmbrowndigital** [comment]
```
55.73 Caused by: java.lang.OutOfMemoryError: Java heap space
55.73   at java.base/java.util.HashMap.newNode(HashMap.java:1909) ~[na:na]
55.73   at java.base/java.util.HashMap.putVal(HashMap.java:637) ~[na:na]
55.73   at java.base/java.util.HashMap.put(HashMap.java:618) ~[na:na]
55.73   at com.starfireaviation.groundschool.service.ImageService.loadData(ImageService.java:73) ~[classes/:na]
55.73   at java.base/java.lang.invoke.LambdaForm$DMH/0x00007f21d8138800.invokeVirtual(LambdaForm$DMH) ~[na:na]
55.73   at java.base/java.lang.invoke.LambdaForm$MH/0x00007f21d8399800.invoke(LambdaForm$MH) ~[na:na]
55.73   at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder) ~[na:na]
55.73   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153) ~[na:na]
55.73   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
55.73   at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
55.73   at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:424) ~[spring-beans-6.0.4.jar:6.0.4]
```

Sending back

**Comment by ameliagbrown** [comment]
Here's the stats on a Macbook running locally without a container
Memory: 16 GB 2133 MHz LPDDR3
```
USER      PID     %CPU     %MEM   VSZ    RSS   TT  STAT STARTED      TIME COMMAND
USER      67894   0.0      20.6 40208936 3461120 s000  S+    7:16PM   1:06.09 /usr/bin/java -jar target/groundschool-0.0.1-SNAPSHOT.jar

**Comment by ameliagbrown** [comment]
Memory screenshots

<img width="1013" alt="Screen Shot 2024-05-10 at 7 56 31 PM" src="https://github.com/freesimpleryan/groundschool-2/assets/143023644/9b1fadb4-8c87-4d0d-bb82-6be425208341">
<img width="1017" alt="Screen Shot 2024-05-10 at 7 56 03 PM" src="https://github.com/freesimpleryan/groundschool-2/assets/143023644/bf9a3d90-82c6-4f81-be1d-7fc576bbb242">
<img width="1007" alt="Screen Shot 2024-05-10 at 7 55 11 PM" src="https://github.com/freesimpleryan/groundschool-2/assets/143023644/b72b6b58-f059-42c6-a275-3c658a54e04a">
